security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_LIBRAIRIAN, ROLE_USER]
        ROLE_LIBRAIRIAN:  [ROLE_USER]
        ROLE_USER:        []

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

        main:
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /auth # The name in routes.yaml is enough for mapping
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            entry_point: jwt
            refresh_jwt:
                check_path: /token/refresh


    access_control:
        # Swagger & doc accessibles publiquement
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/$, roles: PUBLIC_ACCESS }

        # Authentification
        - { path: ^/auth, roles: PUBLIC_ACCESS }
        - { path: ^/token/refresh, roles: PUBLIC_ACCESS }

        # Routes API sécurisées
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/librairian, roles: ROLE_LIBRAIRIAN }
        - { path: ^/api, roles: PUBLIC_ACCESS }
  
